![](https://img.kaikeba.com/web/kkb_index/img_index_logo.png)

# 人工智能基础课机器学习 第二节课作业 股票数据清洗

同学们好，本次作业的主要内容为使用pandas进行数据预处理。希望这两天你们已经从Python的课程内容中回过神来了。
没有数据的分析是无源之水，能够熟练处理数据是成为合格的数据分析师的基本要求，希望大家在今后多多实战，成为数据大师。

本次作业将使用公开标普500的股票数据。
https://www.kaggle.com/dgawlik/nyse#prices-split-adjusted.csv

作业的形式以问答为主，因为不涉及过长的代码，核心是数据的操作，所以这里没有太多的代码模板可供大家参考。
希望大家能从搜索引擎（google/bing）问答社区（stackoverflow）或者[官方文档](https://pandas.pydata.org/pandas-docs/stable/user_guide/index.html)或者我提供的jupyter notebooks 中找到回答问题需要的方法。
请时刻牢记数据的增删改查四种原子操作，思考我们的问题可以被如何分解。

那么首先，我们要import pandas

In [317]:
import pandas as pd

# 1. 从fundemantals.csv开始！

fundemantals.csv 是这些股票的年报数据

请用数据回答以下问题：

1. S&P500股票在2015年`net income`的均值是多少？最大值比最小值多多少？（每问10分，共计20分）
2. S&P500股票在2016年的固定资产（fixed assets）占总资产(total assets)比例的均值是多少？固定资产占总资产比例最小的股票是的代码（ticker symbol）是什么？（每问10分，共计20分）

In [318]:
fund_df = pd.read_csv('fundamentals.csv') #导入数据
data=fund_df.groupby(fund_df['For Year'].apply(lambda x:x if x==2015 else None)) #取年份为2015的数据
print('1.S&P500股票在2015年net income的均值是:')
data['Net Income'].mean()

1.S&P500股票在2015年net income的均值是:

For Year
2015.0    1.575186e+09
Name: Net Income, dtype: float64

In [319]:
print('最大值比最小值多：')
data['Net Income'].max()-data['Net Income'].min()

最大值比最小值多：

For Year
2015.0    7.692200e+10
Name: Net Income, dtype: float64

In [320]:
data=fund_df.groupby(fund_df['For Year'].apply(lambda x :x if x==2016 else None)) #取年份为2016的数据
print('2.S&P500股票在2016年的固定资产（fixed assets）占总资产(total assets)比例的均值是:')
data.apply(lambda x:fund_df['Fixed Assets']/fund_df['Total Assets']).mean(axis=1)

2.S&P500股票在2016年的固定资产（fixed assets）占总资产(total assets)比例的均值是:

For Year
2016.0    0.284154
dtype: float64

In [321]:
t=data.apply(lambda x:fund_df['Fixed Assets']/fund_df['Total Assets']).min(axis=1) #固定资产占总资产比例最小的值
print('最小值为:\n'+str(t)+'\n')
result=fund_df[(fund_df['Fixed Assets']/fund_df['Total Assets']).isin(t)]['Ticker Symbol'] #固定资产占总资产比例为最小值的股票的代码
print('固定资产占总资产比例最小的股票共有{}个,代码分别为：'.format(result.agg("count")))
result

最小值为:
For Year
2016.0    0.0
dtype: float64

固定资产占总资产比例最小的股票共有51个,代码分别为：

56       AIG
57       AIG
58       AIG
59       AIG
112      AMP
113      AMP
114      AMP
115      AMP
250        C
251        C
252        C
253        C
266       CB
267       CB
268       CB
269       CB
947      LEN
948      LEN
949      LEN
950      LEN
1051     MET
1052     MET
1053     MET
1054     MET
1129    NAVI
1130    NAVI
1131    NAVI
1288     PNC
1289     PNC
1290     PNC
1291     PNC
1308     PRU
1309     PRU
1310     PRU
1311     PRU
1478     SYF
1479     SYF
1480     SYF
1481     SYF
1530     TMK
1531     TMK
1532     TMK
1533     TMK
1542     TRV
1543     TRV
1544     TRV
1545     TRV
1737      XL
1738      XL
1739      XL
1740      XL
Name: Ticker Symbol, dtype: object

# 2. 加入securities.csv~

securities.csv包含了这些股票的基本信息

1. 请列举出各个sector中的加入时间最早的股票名称（10分）
2. 请列举出每一个州中加入时间最晚的股票名称（10分）

In [322]:
import numpy as np
#导入数据
sec_df_ = pd.read_csv('securities.csv')
#将日期转为数字，nan的转为0
def datestr2num(s):
    if pd.isnull(s):
        return 0
    else:
        return datetime.datetime.strptime(s,'%Y/%m/%d').toordinal()
a=[]
for i in sec_df_['Date first added']:
    a.append(datestr2num(i))
#添加日期的对应列'ttt'
sec_df_['ttt'] = a

In [323]:
#分组后取'ttt‘列’
data=sec_df_.groupby(['GICS Sector','Security'])[['ttt']].max()
print('各个sector中的加入时间最早的股票名称分别为:')
#取ttt的最小值，即加入时间最早的股票名称，将日期为0的数据替换为1000000，避免影响寻找最小值
data.dropna(0).groupby(['GICS Sector'])[['ttt']].apply(lambda x:x.replace(0,1000000).sort_values(by='ttt')[:1])

各个sector中的加入时间最早的股票名称分别为:

                                                                                        ttt
GICS Sector                 GICS Sector                 Security
Consumer Discretionary      Consumer Discretionary      McDonald's Corp.             719343
Consumer Staples            Consumer Staples            The Clorox Company           718887
Energy                      Energy                      Schlumberger Ltd.            717426
Financials                  Financials                  JPMorgan Chase & Co.         721169
Health Care                 Health Care                 Abbott Laboratories          717061
Industrials                 Industrials                 Honeywell Int'l Inc.         717061
Information Technology      Information Technology      HP Inc.                      720988
Materials                   Materials                   Sherwin-Williams             717152
Real Estate                 Real Estate                 AvalonBay Communities, Inc.  732686
Telecommunications Services Telecommunications Services AT&T Inc                     724244
Utilities                   Utilities                   NextEra Energy               721535

In [324]:
#分组后取'ttt‘列’
data=sec_df_.groupby(['Address of Headquarters','Security'])[['ttt']].max()
print('每一个州中加入时间最晚的股票名称分别为:')
#取ttt的最大值，即加入时间最晚的股票名称
data.groupby(['Address of Headquarters'])[['ttt']].apply(lambda x:x.sort_values(by='ttt')[-1:])

每一个州中加入时间最晚的股票名称分别为:

                                                                                                       ttt
Address of Headquarters        Address of Headquarters        Security
Akron, Ohio                    Akron, Ohio                    Goodyear Tire & Rubber                     0
Allentown, Pennsylvania        Allentown, Pennsylvania        Air Products & Chemicals Inc          724761
Amsterdam, Netherlands         Amsterdam, Netherlands         Mylan N.V.                                 0
Amsterdam, New York            Amsterdam, New York            Mohawk Industries                     735225
Arlington, Virginia            Arlington, Virginia            AES Corp                                   0
Arlington, Virginia[3]         Arlington, Virginia[3]         AvalonBay Communities, Inc.           732686
Armonk, New York               Armonk, New York               International Business Machines            0
Atlanta, Georgia               Atlanta, Georgia               Acuity Brands Inc                     736087
Auburn Hills, Michigan         Auburn Hills, Michigan         BorgWarner                            734490
Austin, Minnesota              Austin, Minnesota              Hormel Foods Corp.                    733470
Austin, Texas                  Austin, Texas                  Whole Foods Market                         0
Baltimore, Maryland            Baltimore, Maryland            Under Armour                          736048
Baton Rouge, Louisiana         Baton Rouge, Louisiana         Albemarle Corp                        736146
Battle Creek, Michigan         Battle Creek, Michigan         Kellogg Co.                                0
Bellevue, Washington           Bellevue, Washington           Expedia Inc.                          732951
Benton Harbor, Michigan        Benton Harbor, Michigan        Whirlpool Corp.                            0
Bentonville, Arkansas          Bentonville, Arkansas          Wal-Mart Stores                       723788
Berwyn, Pennsylvania           Berwyn, Pennsylvania           AMETEK Inc                            735134
Bethesda, Maryland             Bethesda, Maryland             Host Hotels & Resorts                 732755
Beverly, Massachusetts         Beverly, Massachusetts         Affiliated Managers Group Inc         735415
Birmingham, Alabama            Birmingham, Alabama            Vulcan Materials                           0
Boise, Idaho                   Boise, Idaho                   Micron Technology                     728198
Bolingbrook, Illinois          Bolingbrook, Illinois          Ulta Salon Cosmetics & Fragrance Inc  736072
Boston, Massachusetts          Boston, Massachusetts          Iron Mountain Incorporated            733413
Brentwood, Tennessee           Brentwood, Tennessee           Tractor Supply Company                735257
Bridgeport, Connecticut        Bridgeport, Connecticut        People's United Financial             733359
Brookfield, Wisconsin          Brookfield, Wisconsin          Fiserv Inc                                 0
Broomfield, Colorado           Broomfield, Colorado           Level 3 Communications                735542
Buffalo, New York              Buffalo, New York              M&T Bank Corp.                             0
Burbank, California            Burbank, California            The Walt Disney Company               721535
...                                                                                                    ...
Tempe, Arizona                 Tempe, Arizona                 First Solar Inc                       733696
The Woodlands, Texas           The Woodlands, Texas           Anadarko Petroleum Corp                    0
Thousand Oaks, California      Thousand Oaks, California      Amgen Inc                             727199
Toledo, Ohio                   Toledo, Ohio                   Welltower Inc.                        733437
Tulsa, Oklahoma                Tulsa, Oklahoma                ONEOK                                 733846
Tulsa, Oklahoma[5]             Tulsa, Oklahoma[5]             Helmerich & Payne                          0
Tysons Corner, Virginia        Tysons Corner, Virginia        Capital One Financial                      0
Union, New Jersey              Union, New Jersey              Bed Bath & Beyond                          0
Vernier, Switzerland           Vernier, Switzerland           Transocean                            735170
Victor, New York               Victor, New York               Constellation Brands                       0
Voorhees, New Jersey           Voorhees, New Jersey           American Water Works Company Inc      736027
Wallingford, Connecticut       Wallingford, Connecticut       Amphenol Corp                         733315
Waltham, Massachusetts         Waltham, Massachusetts         PerkinElmer                           724792
Warsaw, Indiana                Warsaw, Indiana                Zimmer Biomet Holdings                     0
Washington County, Oregon      Washington County, Oregon      Nike                                  726071
Washington, D.C.               Washington, D.C.               Danaher Corp.                              0
West Falls Church, Virginia    West Falls Church, Virginia    Northrop Grumman Corp.                724822
Westbrook, Maine               Westbrook, Maine               IDEXX Laboratories                    736334
Weston, Massachusetts          Weston, Massachusetts          BIOGEN IDEC Inc.                           0
White Plains, New York         White Plains, New York         Xylem Inc.                            734442
Whitehouse Station, New Jersey Whitehouse Station, New Jersey Merck & Co.                                0
Wilmington, Delaware           Wilmington, Delaware           Du Pont (E.I.)                             0
Wilsonville, Oregon            Wilsonville, Oregon            FLIR Systems                          733409
Winona, Minnesota              Winona, Minnesota              Fastenal Co                           733665
Winston-Salem, North Carolina  Winston-Salem, North Carolina  Hanesbrands Inc                       735677
Woburn, Massachusetts          Woburn, Massachusetts          Skyworks Solutions                    735669
Woonsocket, Rhode Island       Woonsocket, Rhode Island       CVS Health                                 0
Worsley, UK                    Worsley, UK                    Pentair Ltd.                          734777
York, Pennsylvania             York, Pennsylvania             Dentsply Sirona                       733360
Zurich, Switzerland            Zurich, Switzerland            Chubb Limited                         733968

[264 rows x 1 columns]

# 3. merge!

现在你需要同时处理来自两个表中的信息了

1. 请思考，合并两个表的信息的时候，我们应该用什么样的准则对其它们（10分）
2. 请列举每个sector在2013-2016年累计Research&Development的总投入（10分）
3. 请列举出每个sector中，在2013-2016年累计Research&development投入最大的3家公司的名称以及投入的数值（20分）

In [17]:
new_df=pd.merge(fund_df, sec_df_,on='Ticker Symbol') #两个表的相同列是'Ticker Symbol',依据此列进行合并

In [87]:
print('每个sector在2013-2016年累计Research&Development的总投入如下:')
new_df.groupby([new_df['GICS Sector'],new_df['For Year'].apply(lambda x :x if 2016>=x>=2013 else None)])[['Research and Development']].sum()

每个sector在2013-2016年累计Research&Development的总投入如下:

                                      Research and Development
GICS Sector                 For Year
Consumer Discretionary      2013.0                5.725140e+08
                            2014.0                6.176770e+08
                            2015.0                6.699870e+08
                            2016.0                0.000000e+00
Consumer Staples            2013.0                3.582000e+08
                            2014.0                3.621000e+08
                            2015.0                3.614000e+08
                            2016.0                2.650000e+08
Energy                      2013.0                5.712350e+08
                            2014.0                6.289050e+08
                            2015.0                4.821040e+08
                            2016.0                1.026900e+07
Financials                  2013.0                0.000000e+00
                            2014.0                0.000000e+00
                            2015.0                0.000000e+00
                            2016.0                0.000000e+00
Health Care                 2013.0                4.580909e+10
                            2014.0                5.106480e+10
                            2015.0                5.407746e+10
                            2016.0                1.771011e+09
Industrials                 2013.0                1.389331e+10
                            2014.0                1.444683e+10
                            2015.0                1.289366e+10
                            2016.0                1.389100e+09
Information Technology      2013.0                7.018771e+10
                            2014.0                7.516956e+10
                            2015.0                8.140733e+10
                            2016.0                5.505875e+10
Materials                   2013.0                5.744384e+09
                            2014.0                5.675050e+09
                            2015.0                5.445772e+09
                            2016.0                1.644000e+09
Real Estate                 2013.0                6.521000e+07
                            2014.0                2.700000e+07
                            2015.0                2.400000e+07
Telecommunications Services 2013.0                0.000000e+00
                            2014.0                0.000000e+00
                            2015.0                0.000000e+00
Utilities                   2013.0                0.000000e+00
                            2014.0                0.000000e+00
                            2015.0                0.000000e+00

In [184]:
#每个sector中，2013-2016年各个公司累计Research&development投入的数值
data=new_df.groupby([new_df['GICS Sector'],new_df['For Year'].apply(lambda x :x if 2016>=x>=2013 else None),new_df['Security']])[['Research and Development']].sum()
print('每个sector中，在2013-2016年累计Research&development投入最大的3家公司的名称以及投入的数值:')
#分组后Research&development投入的数值排名前三的公司
data.groupby(['GICS Sector','For Year'])[['Research and Development']].apply(lambda x:x.sort_values(by='Research and Development')[-3:])

每个sector中，在2013-2016年累计Research&development投入最大的3家公司的名称以及投入的数值:

                                                                                                           Research and Development
GICS Sector                 For Year GICS Sector                 For Year Security
Consumer Discretionary      2013.0   Consumer Discretionary      2013.0   Yum! Brands Inc                              0.000000e+00
                                                                          Hasbro Inc.                                  2.075910e+08
                                                                          Garmin Ltd.                                  3.649230e+08
                            2014.0   Consumer Discretionary      2014.0   Yum! Brands Inc                              0.000000e+00
                                                                          Hasbro Inc.                                  2.225560e+08
                                                                          Garmin Ltd.                                  3.951210e+08
                            2015.0   Consumer Discretionary      2015.0   Yum! Brands Inc                              0.000000e+00
                                                                          Hasbro Inc.                                  2.429440e+08
                                                                          Garmin Ltd.                                  4.270430e+08
                            2016.0   Consumer Discretionary      2016.0   The Walt Disney Company                      0.000000e+00
                                                                          Urban Outfitters                             0.000000e+00
                                                                          Viacom Inc.                                  0.000000e+00
Consumer Staples            2013.0   Consumer Staples            2013.0   Mead Johnson                                 1.002000e+08
                                                                          Campbell Soup                                1.280000e+08
                                                                          The Clorox Company                           1.300000e+08
                            2014.0   Consumer Staples            2014.0   Mead Johnson                                 1.151000e+08
                                                                          Campbell Soup                                1.220000e+08
                                                                          The Clorox Company                           1.250000e+08
                            2015.0   Consumer Staples            2015.0   Mead Johnson                                 1.084000e+08
                                                                          Campbell Soup                                1.170000e+08
                                                                          The Clorox Company                           1.360000e+08
                            2016.0   Consumer Staples            2016.0   Whole Foods Market                           0.000000e+00
                                                                          Campbell Soup                                1.240000e+08
                                                                          The Clorox Company                           1.410000e+08
Energy                      2013.0   Energy                      2013.0   Williams Cos.                                0.000000e+00
                                                                          Helmerich & Payne                            1.523500e+07
                                                                          Baker Hughes Inc                             5.560000e+08
                            2014.0   Energy                      2014.0   Williams Cos.                                0.000000e+00
                                                                          Helmerich & Payne                            1.590500e+07
                                                                          Baker Hughes Inc                             6.130000e+08
...                                                                                                                             ...
Materials                   2016.0   Materials                   2016.0   WestRock Company                             0.000000e+00
                                                                          Air Products & Chemicals Inc                 1.320000e+08
                                                                          Monsanto Co.                                 1.512000e+09
Real Estate                 2013.0   Real Estate                 2013.0   Federal Realty Investment Trust              0.000000e+00
                                                                          Vornado Realty Trust                         3.221000e+07
                                                                          Weyerhaeuser Corp.                           3.300000e+07
                            2014.0   Real Estate                 2014.0   Apartment Investment & Mgmt                  0.000000e+00
                                                                          HCP Inc.                                     0.000000e+00
                                                                          Weyerhaeuser Corp.                           2.700000e+07
                            2015.0   Real Estate                 2015.0   Apartment Investment & Mgmt                  0.000000e+00
                                                                          Welltower Inc.                               0.000000e+00
                                                                          Weyerhaeuser Corp.                           2.400000e+07
Telecommunications Services 2013.0   Telecommunications Services 2013.0   Frontier Communications                      0.000000e+00
                                                                          Level 3 Communications                       0.000000e+00
                                                                          Verizon Communications                       0.000000e+00
                            2014.0   Telecommunications Services 2014.0   Frontier Communications                      0.000000e+00
                                                                          Level 3 Communications                       0.000000e+00
                                                                          Verizon Communications                       0.000000e+00
                            2015.0   Telecommunications Services 2015.0   Frontier Communications                      0.000000e+00
                                                                          Level 3 Communications                       0.000000e+00
                                                                          Verizon Communications                       0.000000e+00
Utilities                   2013.0   Utilities                   2013.0   Ameren Corp                                  0.000000e+00
                                                                          Eversource Energy                            0.000000e+00
                                                                          Xcel Energy Inc                              0.000000e+00
                            2014.0   Utilities                   2014.0   Ameren Corp                                  0.000000e+00
                                                                          Entergy Corp.                                0.000000e+00
                                                                          Xcel Energy Inc                              0.000000e+00
                            2015.0   Utilities                   2015.0   Ameren Corp                                  0.000000e+00
                                                                          Eversource Energy                            0.000000e+00
                                                                          Xcel Energy Inc                              0.000000e+00

[119 rows x 1 columns]

# 4. 现在让我们来看看更加复杂的数据

请导入price.csv，然后结合你的聪明才智回答以下问题（附加题，40分）

假设你是某基金公司的老板，现在对于每只股票，你都专门安排了一位负责它的交易员。公司规定每一位交易员手中的资金要么全部买入要么全部卖出（空仓，转化为现金）。假设2016年每一位交易员手中都有10000美元，假设他们都能够看到2016年全年的数据，假设他们都能抓住每一次机会，那么请问2016年底时，赚钱最多的股票是哪一只，赚了多少钱？